services:
  site:
    image: peach-captcha
    ports:
      - "80:80"
    volumes:
      - "../:/var/www/html/"

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: peach
    ports:
      - "3306:3306"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d